brick:
	g++ -c brickBreaker.cpp
	g++ brickBreaker.o -o brickBreaker -lsfml-graphics -lsfml-window -lsfml-system -lsfml-network

tron:
	g++ -c tron.cpp
	g++ tron.o -o tron -lsfml-graphics -lsfml-window -lsfml-system -lsfml-network
