brick:
	g++ -c brickBreaker.cpp
	g++ brickBreaker.o -o brickBreaker -lsfml-graphics -lsfml-window -lsfml-system -lsfml-network

tron:
	gcc -c virtualMemory.c virtualMemory.h
	g++ -c tron.cpp
	g++ virtualMemory.o tron.o -o tron -lsfml-graphics -lsfml-window -lsfml-system -lsfml-network -lpthread -fpermissive
