tic:
	g++ -c ticTacToe.cpp
	g++ ticTacToe.o -o ticTacToe -lsfml-graphics -lsfml-window -lsfml-system

rick:
	g++ -c miniRick.cpp
	g++ miniRick.o -o miniRick -lsfml-graphics -lsfml-window -lsfml-system
